server:
  port: 8088

spring:
  messages:
    encoding: utf-8
    basename: static/i18n/messages
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://10.0.59.161:3307/yuque?useSSL=false&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&transformedBitIsBoolean=true&tinyInt1isBit=false&allowMultiQueries=true&serverTimezone=GMT%2B8&allowPublicKeyRetrieval=true
    username: root
    password: 123456
#    driver-class-name: org.postgresql.Driver
#    url: jdbc:postgresql://10.0.59.63:5432/test?useSSL=false&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&transformedBitIsBoolean=true&tinyInt1isBit=false&allowMultiQueries=true&serverTimezone=GMT%2B8&allowPublicKeyRetrieval=true
#    username: postgres
#    password: postgres
logging:
  level:
    sql: debug
    org.springframework.jdbc: debug

#xxl:
#  job:
#    accessToken: default_token
#    admin:
#      # 调度中心服务地址
#      addresses: http://127.0.0.1:8080/xxl-job-admin
#    executor:
#      address: ''
#      # 必须唯一 执行器名称
#      appname: jobhandel
#      ip: ''
#      logpath: /data/applogs/xxl-job/jobhandler
#      logretentiondays: 30
#      # 执行器回调端口,用于接受调度消息
#      port: 9998



